sudo: required
services:
    - docker

before_install:
    - docker build -t msbeni/dockerized_react -f Dockerfile.dev .

script:
    - docker run -e CI=true msbeni/dockerized_react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "dockerized_react"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-west-2-306476627547"
    bucket_path: "dockerized_react"
    on:
        branch: master
