sudo: required
services:
    - docker

before_install:
    - docker build -t msbeni/dockerized_react -f Dockerfile.dev .

script:
    - docker run -e CI=true msbeni/dockerized_react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "dockerizes_react"
    env: "DockerizesReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-824060776175"
    bucket_path: "dockerizes_react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
